local rootPath = path.join(os.projectdir(), "Platform") --local lib_path = path.join(os.projectdir(),"dev","tools","DataReport")
local frameworkPath = path.join(os.projectdir(), "Framework")
-- target("memoryTest")
--     set_group("test")
--     set_kind("binary")
--     add_files(path.join(rootPath, "TestMemoryManager.cpp"))
--     add_deps("framework")
--     add_includedirs(frameworkPath)
--     add_filegroups("src", {rootdir = rootPath})

target("windows")
    set_kind("binary")
    add_files(path.join(rootPath, "Windows/*.cpp"))
    add_headerfiles(path.join(rootPath, "Windows/*.hpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = path.join(rootPath, "Windows")})
    set_group("platform")
    set_default(true)

target("empty")
    set_kind("binary")
    add_files(path.join(rootPath, "Empty/*.cpp"))
    add_headerfiles(path.join(rootPath, "Empty/*.hpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = path.join(rootPath, "Empty")})
    set_group("platform")