local rootPath = path.join(os.projectdir(), "Test") --local lib_path = path.join(os.projectdir(),"dev","tools","DataReport")
local frameworkPath = path.join(os.projectdir(), "Framework")
target("memoryTest")
    set_group("test")
    set_kind("binary")
    add_files(path.join(rootPath, "TestMemoryManager.cpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = rootPath})

target("D3DTest")
    set_group("test")
    set_kind("binary")
    add_files(path.join(rootPath, "TestD3D.cpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = rootPath})
    -- set_toolchains("clang")
    add_links("user32","d3d11","d3dcompiler")
    after_build(function(target)
        if is_mode("debug") then
            os.cp(path.join(rootPath, "Shader/*.*") , "$(buildir)/windows/x64/release")
        else
            os.cp(path.join(rootPath, "Shader/*.*") , "$(buildir)/windows/x64/debug")
        end
    end)
    -- os.cp("$(rootPath)", "$(buildir)/windows/x64/debug")
