local rootPath = path.join(os.projectdir(), "Test") --local lib_path = path.join(os.projectdir(),"dev","tools","DataReport")
local frameworkPath = path.join(os.projectdir(), "Framework")
target("memoryTest")
    set_group("test")
    set_kind("binary")
    add_files(path.join(rootPath, "TestMemoryManager.cpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = rootPath})

target("D3DTest")
    set_group("test")
    set_kind("binary")
    add_files(path.join(rootPath, "TestD3D.cpp"))
    add_deps("framework")
    add_includedirs(frameworkPath)
    add_filegroups("src", {rootdir = rootPath})